"""Add active lease unique index

Revision ID: 27bbb21ac542
Revises: 527dd28ccced
Create Date: 2026-09-19 19:49:37.646084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27bbb21ac542'
down_revision: Union[str, Sequence[str], None] = '527dd28ccced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_lease_active_unit', 'leases', ['unit_id'], unique=True, sqlite_where=sa.text('is_active IS 1'), postgresql_where=sa.text('is_active IS 1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
    'uq_lease_active_unit',
    table_name='leases',
    sqlite_where=sa.text('is_active IS 1'),
    postgresql_where=sa.text('is_active IS 1'),
)
    # ### end Alembic commands ###
